### ISSUE TITLE
grid_base warning

### ISSUE THREAD

**Issue by egull** [aeantipov/opendf#3] opened 2016-11-26 21:29 UTC
Not sure if the following is a desired behavior or a real problem. With the OpenDF code in debug mode, running a DF calculation with >1 bosonic frequency gives warnings of the type:

Calculating bubbles
/home/egull/opendf/build_debug/gftools-prefix/src/gftools/gftools/grid_base.hpp:221: Couldn't shift point{(-0,-79.7965)<-[0]} by (-0,-1.25664) got (-0,-81.0531)
/home/egull/opendf/build_debug/gftools-prefix/src/gftools/gftools/grid_base.hpp:221: Couldn't shift point{(-0,-79.7965)<-[0]} by (-0,-1.25664) got (-0,-81.0531)
...etc

whereas running it in the release mode gives no warnings. Both seem to produce results.

So: 
Should it produce warnings at all? 
Should it produce warnings in the release mode too?
Are the results correct (or at least as intended)?

**Comment by aeantipov** [comment] 2016-11-26 22:20
The warning is caused by the fact that when there's more than one bosonic frequency, the shift of the fermionic GF is required, i.e. G(w+Omega, k+q). Since in this case w+Omega maybe outside of the grid this shift is not possible for some points at the end of the fermionic grid, instead the zero is returned. The warning is thrown to notify of this. So this is an intended behavior. It is not done in the release mode, because it's a costly range check.

**Comment by egull** [comment] 2016-11-26 22:24
Ok, makes sense. This is also most likely the source of the high frequency problem that we have in James' chi. Just to make sure again: even in release mode, zero is returned, not some undefined behavior?

**Comment by aeantipov** [comment] 2016-11-26 22:29
Yes. It is zero. This could be avoided by doing FFT instead of a shift. But this requires attaching tails, which in generally we don't know for the vertex. Alright, closing this one.

**Closed as completed by aeantipov** 2016-11-26 22:29 UTC
